OnlineRealEstate/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using OnlineRealEstateEntity;
using OnlineRealEstateRepositary;

namespace OnlineRealEstate.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            LandRepositary landRepositary = new LandRepositary();
            List<Land> land=landRepositary.GetLandDetail();
            ViewData["land"] = land;
            return View();
        }
    }
}

OnlineRealEstate/Controllers/LandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineRealEstateRepositary;
using OnlineRealEstateEntity;

namespace OnlineRealEstate.Controllers
{
    public class LandController : Controller
    {
        public ActionResult Index(Land land)
        {
            return RedirectToAction("DisplayLandDetails");
        }
        // GET: Land
        public ActionResult DisplayLandDetails()
        {
            IEnumerable<Land> land = LandRepositary.GetLandDetails();
            ViewBag.Land = land;
            ViewData["land"] = land;
            TempData["land"] = land;
            return RedirectToAction("DisplayDetails");
        }
        
        public ActionResult DisplayDetails()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create_Post([Bind(Include = "location,area,propertyType")]Land land)
        {
           
            
            LandRepositary.Add(land);   
            return RedirectToAction("DisplayLandDetails");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Land land = LandRepositary.GetLandById(id);
            return View(land);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            LandRepositary.Delete(id);
            return RedirectToAction("DisplayLandDetails");
        }
        [HttpPost]
        public ActionResult Update([Bind(Exclude = "propertyType")]Land land)
        {
            LandRepositary.Update(land);
            return RedirectToAction("DisplayLandDetails");

        }
         
    }
}

OnlineRealEstate/Controllers/UserController.cs
using System.Collections.Generic;
using OnlineRealEstateEntity;
using OnlineRealEstateRepositary;
using OnlineRealEstateBL;
using System.Web.Mvc;

namespace OnlineRealEstate.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SignUp()
        {
            IEnumerable<Land> land = LandRepositary.GetLandDetails();
            ViewBag.Land = land;
            return View();
        }
        [HttpGet]
        public ActionResult SignUp(UserManager userManager)
        {
            if (ModelState.IsValid)
            {
                int userId = UserBL.SignUp(userManager);
                if (userId > 0)
                {
                    ViewBag.Message = "Register successfull";
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            ViewBag.Message = "Login Successfull";
            return View();
        }
    }
}

OnlineRealEstate/Views/Home/Index.cshtml
@model OnlineRealEstateEntity.Land

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Master.cshtml";
}

<head>
    <style>
        #table {
            border-spacing: 10px;
            padding: 10px;
        }
    </style>
</head>

<h2>DisplayDetails</h2>
<table class="table">

    <tr>
        <td> Land ID</td>
        <td>Property Type</td>
        <td>Location</td>
        <td> Area(in sq.ft)</td>

    </tr>
    Temp data
    @foreach (OnlineRealEstateEntity.Land item in (List<OnlineRealEstateEntity.Land>)ViewData["land"])
    {
        <tr>
            <td> @item.landId</td>
            <td>@item.propertyType</td>
            <td>@item.location</td>
            <td> @item.area</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.landId })
                @Html.ActionLink("Delete", "Delete", new { id = item.landId })
            </td>

        </tr>
    }
</table>

OnlineRealEstate/Views/Land/Create.cshtml
@model OnlineRealEstateEntity.Land

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using(Html.BeginForm("Create_Post","Land",FormMethod.Post))
{

<table>
    <tr>
        <td>
            @Html.Label("Land id")
        </td>
        <td>
            @Html.TextBoxFor(Model => Model.landId)
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Land area in sq.ft")
        </td>
        <td>
            @Html.TextBoxFor(Model => Model.area)
        </td>
    </tr>


    <tr>
        <td>
            @Html.Label("Land Property type")
        </td>
        <td>
            @Html.TextBoxFor(Model => Model.propertyType)
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Land location")
        </td>
        <td>
            @Html.TextBoxFor(Model => Model.location)
        </td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink("Back", "DisplayLandDetails")
        </td>
        <td>
            <input type="submit" id="=submit" />
        </td>
    </tr>
</table>
}

OnlineRealEstate/Views/Land/DisplayDetails.cshtml
@model OnlineRealEstateRepositary.LandRepositary

@{
    ViewBag.Title = "DisplayDetails";
}
@Html.ActionLink("Add new details","Create")
<head>
    <style>
        #table {
            border-spacing: 10px;
            padding: 10px;
        }
    </style>
</head>

<h2>DisplayDetails</h2>
<table class="table">

    <tr>
        <td> Land ID</td>
        <td>Property Type</td>
        <td>Location</td>
        <td> Area(in sq.ft)</td>

    </tr>
    Temp data
    @foreach (OnlineRealEstateEntity.Land item in (List<OnlineRealEstateEntity.Land>)TempData["land"])
    {
        <tr>
            <td> @item.landId</td>
            <td>@item.propertyType</td>
            <td>@item.location</td>
            <td> @item.area</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.landId })
                @Html.ActionLink("Delete", "Delete", new { id = item.landId })
            </td>

        </tr>
    }
</table>

OnlineRealEstate/Views/Land/DisplayLandDetails.cshtml
@model IEnumerable<OnlineRealEstateEntity.Land>

@{
    ViewBag.Title = "DisplayLandDetails";
}
<head>
    <style>
        #table {
            border-spacing: 10px;
            padding: 10px;
        }
    </style>
</head>

<h2>DisplayLandDetails</h2>

<table border="1" class="table">
    <tr>
        <td> Land ID</td>
        <td>Property Type</td>
        <td>Location</td>
        <td> Area(in sq.ft)</td>

    </tr>
    @foreach (OnlineRealEstateEntity.Land item in (List<OnlineRealEstateEntity.Land>)ViewData["land"])
    {
        <tr>
            <td> @item.landId</td>
            <td>@item.propertyType</td>
            <td>@item.location</td>
            <td> @item.area</td>

        </tr>
    }
    </table>
<table border="1" class="table">
   View Bag
    <tr>
        <td> Land ID</td>
        <td>Property Type</td>
        <td>Location</td>
        <td> Area(in sq.ft)</td>

    </tr>
    @foreach (OnlineRealEstateEntity.Land item in ViewBag.land)
    {
        <tr>
            <td> @item.landId</td>
            <td>@item.propertyType</td>
            <td>@item.location</td>
            <td> @item.area</td>

        </tr>
    }
</table>

OnlineRealEstate/Views/Land/Edit.cshtml
@model OnlineRealEstateEntity.Land

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm("Update","Land",FormMethod.Post))
{
    @Html.HiddenFor(Model=>Model.landId)
<table>
    <tr>
        <td>Land Area</td>
        <td>
            @Html.EditorFor(Model => Model.area)
        </td>
    </tr>
    <tr>
        <td>Property type</td>
        <td>
            @Html.EditorFor(Model => Model.propertyType)
        </td>
    </tr>
    <tr>
        <td>location</td>
        <td>
            @Html.EditorFor(Model => Model.location)
        </td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink("Cancel", "DisplayLandDetails")
        </td>
        <td>
            <input type="submit"value="Submit" />
        </td>
    </tr>

</table>
}

OnlineRealEstate/Views/Shared/View.cshtml
@model OnlineRealEstateRepositary.LandRepositary
    <head>
        <style>
            .properties
            {
                padding:10px;
                font-family:Arial;
                color:white;
            }
            .text {
                padding: 25px;
                font-family: Calibri;
                line-height: 50px;
                color: white;
            }
        </style>
    </head>
<h3 class="properties">Benefits of Account</h3>
<div class="text">
    Post one Single Property for FREE<br />
    Set property alerts for your requirement<br />
    Get accessed by over 1 Lakh buyers<br/>
</div>

OnlineRealEstate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

OnlineRealEstate/Views/Shared/_Master.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Styles/Master.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header class="header">
        <div>
            <h1 class="headerText">Online Real Estate</h1>
            <nav style="padding:5px;">
                <h2 class="link">
                    @Html.ActionLink("Home", "Index")
                    @Html.ActionLink("SignUp", "SignUp")
                    @Html.ActionLink("LogIn", "Login")
                </h2>
            </nav>
        </div>

    </header>
    <div>
        @RenderBody()
    </div>
</body>
</html>

OnlineRealEstate/Views/User/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Master.cshtml";
}

<h2>Welcome</h2>

OnlineRealEstate/Views/User/Login.cshtml
@model OnlineRealEstateEntity.UserManager

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Master.cshtml";
}
<body>
<h2>Login</h2>
@using (Html.BeginForm("Login", "User", FormMethod.Get))
{
    <table>
        <tr>
            <td>
                @Html.Label("Name")
            </td>
            <td>
                @Html.TextBoxFor(Model => Model.name)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Password")
            </td>
            <td>
                @Html.TextBoxFor(Model => Model.password)
            </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Back", "Index")
            </td>
            <td>
                <input type="submit" id="=submit" />
            </td>
        </tr>
    </table>

}

</body>

OnlineRealEstate/Views/User/SignUp.cshtml
@model OnlineRealEstateEntity.UserManager

@{
    ViewBag.Title = "SignUp";
   
}
<link rel="stylesheet" type="text/css" href="~/Styles/SignUp.css" />
@Html.ValidationSummary(true)
@if (ViewBag.Message != null)
{
    Response.Write(ViewBag.Message);

}

    <body>
        <h2 style="font-family:Calibri;">SignUp</h2>
        <section style="float:left;background-color:palevioletred;border:groove;">
            @Html.Partial("View")
        </section>

        <article>
            @using (Html.BeginForm("SignUp", "User", FormMethod.Get))
            {
                <table align="center" cellspacing="10" cellpadding="10" style="font-family:Calibri;background-color:palevioletred;border:groove;color:white">


                    <tr>
                        <td>
                            @Html.LabelFor(Model => Model.name)
                        </td>
                        <td>
                            @Html.TextBoxFor(Model => Model.name, htmlAttributes: new { style = "border-radius:5px;padding:5px" })
                            @Html.ValidationMessageFor(model => model.name)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(Model => Model.email)
                        </td>
                        <td>
                            @Html.TextBoxFor(Model => Model.email, htmlAttributes: new { style = "border-radius:5px;padding:5px" })
                            @Html.ValidationMessageFor(model => model.email)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(Model => Model.phoneNumber)
                        </td>
                        <td>
                            @Html.TextBoxFor(Model => Model.phoneNumber, htmlAttributes: new { style = "border-radius:5px;padding:5px" })
                            @Html.ValidationMessageFor(model => model.phoneNumber)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(Model => Model.role)
                        </td>
                        <td>
                            Buyer @Html.RadioButtonFor(Model => Model.role, "Buyer", htmlAttributes: new { style = "border-radius:5px;padding:5px" })
                            Seller @Html.RadioButtonFor(Model => Model.role, "Seller", htmlAttributes: new { style = "border-radius:5px;padding:5px" })
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(Model => Model.location)

                        </td>
                        <td>
                            @Html.EnumDropDownListFor(Model => Model.location, "Select Location", htmlAttributes: new { style = "border-radius:5px;padding:5px" })
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(Model => Model.password)

                        </td>
                        <td>
                            @Html.TextBoxFor(Model => Model.password, htmlAttributes: new { style = "border-radius:5px;padding:5px" })
                            @Html.ValidationMessageFor(model => model.password)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("Back", "Index")
                        </td>
                        <td>
                            <input type="submit" id="=submit" style="color:palevioletred;background-color:white;padding:8px;" />
                        </td>
                    </tr>
                </table>
            }
        </article>

    </body>